### ISSUE TITLE
Migrate domains, websites, mails and databases to Hetzner web hosting

### ISSUE THREAD

**Issue by Jewdody** [hetzneronline/community-content#1008]
![Error Reply 2](https://github.com/user-attachments/assets/11499a60-5c44-4986-8940-e9037d2753ec)
![Error Reply](https://github.com/user-attachments/assets/d584741c-7e82-4426-a490-e5de42af7433)
## Problem I could not login to my website account (JEWDODY.COM) since your server is always down
my account is https://jewdody.com/jewadminbk/

## Suggested Fix I need to

**Comment by svenja11** [comment]
Hello @Jewdody 
I'm sorry to hear about the issues you're experiencing with your server. This repository is dedicated to tutorials at [community.hetzner.com/tutorials](https://community.hetzner.com/tutorials) but you can submit a support ticket to our support team as explained at [hetzner.com/support-center](https://www.hetzner.com/support-center/) and they will do their best to help.
