### ISSUE TITLE
Confusion in template

### ISSUE THREAD

**Issue by lenusch** [hetzneronline/community-content#103]
_["If you have translated the tutorial into other languages, please enter the languages according to ISO 639-1 here."]_ 

This can be missunderstood. "other" language is not there, therefore nothing was inserted. Do we have to insert anything here or not? Can it be empty? 

(@n-se )

**Comment by Billito00** [comment]
Thank you for pointing that out.

**Comment by fdrechsler** [comment]
`available_languages` is an array of all available languages including the language of the tutorial itself. However, the Parser in the Background is very forgiving. 

You can omit the line if you don't have more than one language.

Also, don't worry too much. The Community Manager is presented a Review Environment, and he changes necessary metadata for you if you miss something.
