### ISSUE TITLE
Tutorial "install-kubernetes-cluster" missing "hcloud network add-subnet"

### ISSUE THREAD

**Issue by mdll** [hetzneronline/community-content#201]
I tested the tutorial "install-kubernetes-cluster", but the server creation failed.
I think there is a command missing that created a subnet in the network "Kubernetes".

**Comment by n-se** [comment]
What exactly did you execute? Did you specify a network ID?

**Comment by n-se** [comment]
Subnet is only created automatically via webinterface, I added the missing command to the tutorial. Thank you for reporting :)
