### ISSUE TITLE
"enabling iGPU" tutorial seems out of date

### ISSUE THREAD

**Issue by dholbach** [hetzneronline/community-content#208]
Comparing https://community.hetzner.com/tutorials/howto-enable-igpu with the reality on an `ubuntu-1804` system on a `cx11` machine, I found the following differences:

- `i915` is not blacklisted:
  ```sh
  # grep -r i915 /etc/modprobe.d/
  # 
  ```
- `nomodeset` is not used in `grub` config:
  ```sh
  # grep nomodeset /etc/default/grub 
  # 
  ```
- To get the `i915` kernel module, users need to install `linux-image-generic`:
  ```sh
  apt install linux-image-generic
  ```

Unfortunately that's all not enough to enable the GPU, so I'm a bit stuck. Help? :innocent: 

CCing @BackInBash who wrote the original tutorial.

**Comment by n-se** [comment]
I am not sure if this even works on a virtual server.

**Comment by dholbach** [comment]
Well-spotted, @n-se:

> Requirements
> - A dedicated server with an Intel CPU
