### ISSUE TITLE
Formatting of filenames should follow a standard pattern

### ISSUE THREAD

**Issue by fdrechsler** [hetzneronline/community-content#23]
Before merging the Pull Requests the Filenames should be converted into a consistent format.

I suggest using dash-separated file names in pure lowercase in the following order:

1. Title dashed
2. Part dashed (optional, padded, padded to length 2 with 00)
3. using a **.de** for other languages (optional, ISO 639-1:2002)  
4. ending with **.extension** (jpg,mp4,gif,webm,md,..) 

So the tutorial "How to Drill a Hole in a Wall" which is available in `en` and `de` and has 2 Parts will become these filenames:

`how-to-drill-a-hole-in-a-wall-01.de.md`
`how-to-drill-a-hole-in-a-wall-01.en.md`
`how-to-drill-a-hole-in-a-wall-02.de.md`
`how-to-drill-a-hole-in-a-wall-02.en.md`

**Open for Suggestions**

**Comment by tonobo** [comment]
Maybe put them in a folder?

Something like:
```
how-to-drill-a-hole-in-a-wall/01-de.md
how-to-drill-a-hole-in-a-wall/01.en.md
how-to-drill-a-hole-in-a-wall/02.de.md
how-to-drill-a-hole-in-a-wall/02.en.md
```

**Comment by fdrechsler** [comment]
Okay, let's take the Scheme @tonobo suggested 👍

**Comment by leojakeson** [comment]
Few more questions:

1) What about tutorials that only have one part and are only in one language - should they get their own separate folder too?

2) Does a tutorial that is currently only available in German get an English filename?

3) I prefer _en to .en, would that work as well?

how-to-drill-a-hole-in-a-wall/01_en.md
how-to-drill-a-hole-in-a-wall/01_de.md
how-to-drill-a-hole-in-a-wall/02_en.md
how-to-drill-a-hole-in-a-wall/02_de.md
how-to-hammer-a-nail-in-a-wall/01_en.md
how-to-hang-a-picture-frame/01_de.md

**Comment by Kjarrigan** [comment]
> What about tutorials that only have one part and are only in one language - should they get their own separate folder too?
Yes, because there is always the chance that someone will translate it and moving it later seems like an unnecessary thing. Just always create a folder seems like a simple rule. No exceptions.

> Does a tutorial that is currently only available in German get an English filename?
Yes, as the Guideline says default is english - `All tutorials should be written in English.`

**Comment by fdrechsler** [comment]
Please stay with `.en` that's because in URLs if they are underlined as Links, you can not see Underscores in some cases.

**Comment by Kjarrigan** [comment]
Another remark though - what about the assets? Wouldn't it be easiest to move them to the folder too? So everything related to a tutorial is in one place. Otherwise the assets folder will be pure chaos in no time.

**Comment by fdrechsler** [comment]
Yep i allready did so in #26

**Comment by leojakeson** [comment]
That's very different from what I was originally told, so thank you both for clarifying.

**Comment by fdrechsler** [comment]
No worries @leojakeson, it's open source and things are evolving all the time.
