### ISSUE TITLE
lockout

### ISSUE THREAD

**Issue by Stefan-CPlanet** [hetzneronline/community-content#232]
This needs to be edited, following this one you add a static route you won't be able to enter pfsense from lan or wan.
to fix from console run pfctl -d to disable firewall, and then disable anti lockout rule from general settings  in order to always allow from lan, not to follow the rule that won't work

**Comment by n-se** [comment]
What tutorial are you talking about?

**Comment by Stefan-CPlanet** [comment]
https://github.com/hetzneronline/community-content/pull/180/commits/a9f29965321a91e5cb380a18f2cf07605f3c497b

**Comment by n-se** [comment]
I am not sure if I understood what you are referring to. What should change if you **disable** a rule which just allows incoming traffic?

Have you edited this rule?
```
Go to `Firewall -> Rules -> LAN` and edit the rule with description `Default allow LAN to any rule`.
Change the source from `LAN net` to `any`. Save and apply the changes.
```

**Comment by n-se** [comment]
If there are any further issues with this tutorial please let us know. Closing this now...
