### ISSUE TITLE
Tutorial Basic Cloud Config  seed command to deactivate PasswordAuthentication does not work

### ISSUE THREAD

**Issue by stefanSchuhbaeck** [hetzneronline/community-content#242]
The seed command to seed command to deactivate PasswordAuthentication does not work 
if the `sshd_conf` contains the line `#PasswordAuthentication yes`. The leading `#` is not matched by 
`sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config`

Pull Request #241

**Comment by n-se** [comment]
Closed via https://github.com/hetzneronline/community-content/pull/241
