### ISSUE TITLE
Add netplan configuration for guests to Proxmox tutorial

### ISSUE THREAD

**Issue by rook59** [hetzneronline/community-content#259]
The Proxmox tutorial currently only deals with network configuration via `/etc/network/interfaces`, from Ubuntu 18.04 on, network configuration on Ubuntu must be done with netplan by default.

An example configuration with netplan should be added to the Proxmox tutorial for the different scenarios.

**Comment by asciiprod** [comment]
Promox is intended to be installed on top of Debian. Installation on top of Ubuntu is not supported.

**Comment by rook59** [comment]
This was actually a request for an example netplan configuration in a **guest system (virtual machine)** from a customer. No one wants to install Proxmox on top of Ubuntu.
