### ISSUE TITLE
Formatting/display issue on published OpenSSH U2F tutorial

### ISSUE THREAD

**Issue by Erisa** [hetzneronline/community-content#268]
Hi!
On the published version of my tutorial: https://community.hetzner.com/tutorials/openssh-with-u2f-security-key-debian-10

There is a formatting/display issue here:
![image](https://user-images.githubusercontent.com/14004943/95692342-0016a100-0c1d-11eb-8ba0-fc0d3ed2f55f.png)

This same error doesn't show up on the [test suite](https://community.hetzner.com/markdown-test-suite/) which is rather odd.

Test suite shows this:
![image](https://user-images.githubusercontent.com/14004943/95692361-1de40600-0c1d-11eb-8e4f-817af4aacd46.png)
Which is the expected result.

**Comment by rook59** [comment]
It is broken on GitHub too, https://github.com/hetzneronline/community-content/blob/master/tutorials/openssh-with-u2f-security-key-debian-10/01.en.md#step-11---upgrading-and-preparing-the-package-repositories
Really strange that it is working in the test suite, I will forward this.

I expect we can simply fix it ourself with adding a `>` before the three ` of your qouted code block.

**Comment by Erisa** [comment]
Apologies for the late response, the change you made doesn't appear to be on the website or just doesn't work. Not sure I understand personally what causes it.

**Comment by rook59** [comment]
The test suite is still a bit outdated (it is on their ToDo), but according to the team this new patch should fix it on the community site.
