### ISSUE TITLE
Does the content from my own blog qualifies as a legitimate contribution for Hetzner Community Posts?

### ISSUE THREAD

**Issue by jtnydv** [hetzneronline/community-content#281]
I run a blog at https://blog.jtnydv.com. I wanted to know if any past/future posts qualify as a valid community content contribution?

I will still follow the process mentioned in the `contribution.en.md` file; however, I wanted to make sure that it can be duplicated from my own creation/blog.

Regards,
Jatin Yadav

**Comment by leojakeson** [comment]
Hello Jatin,

Thanks for reaching out about this. As mentioned in our guidelines:

> We will only accept original work.
This means that you cannot re-submit any work that is published somewhere else on the the web.

So duplicating posts is not something we support, sorry.

However, if you have an idea for a future post, you are welcome to publish it with us, and then link to it from your blog.

I hope that answers your question sufficiently.

**Comment by jtnydv** [comment]
> "publish it with us, and then link to it from your blog."

So if I publish on Hetzner first and then put a copy on to my website and hat put in a link back to the Hetzner's page, will that be fine?

My concern is, I would like to have my content on my website as well. I do not have any problems in posting it on Hetzner first.

**Comment by leojakeson** [comment]
Publishing it in two places doesn't work for us, sorry.

You can link to it from your blog, but if you publish it there as well, then it will be duplicated, and we're not looking for that.

**Comment by jtnydv** [comment]
Okay, understood. I'll be submitting my posts for Hetzner soon. Thanks for the quick response.
