### ISSUE TITLE
Ansible-Role as tutorial?

### ISSUE THREAD

**Issue by zapalotta** [hetzneronline/community-content#289]
Hi,

I created an ansible role for setting up a complete borg backup on a storage box (https://github.com/zapalotta/hetznerbackup). 

Writing a tutorial would be kind of trivial, is there any rule for this? Or shall I write one (it will be very short)?

Best,
Dirk

**Comment by rook59** [comment]
Nice ansible role! Don't forget to add some tags to make it easier to find.
I think your README already explains everything needed to use this role. From our contributing guidelines:    
> We will only accept original work.
> This means that you cannot re-submit any work that is published somewhere else on the the web.

@Billito00 what do you think?

**Comment by Billito00** [comment]
As @rook59 already mentioned we only accept original work. 
I would suggest that you write a short how to tutorial around the existing content. Make sure that beginners can follow this tutorial step by step. 
Please also take a look at our tutorial [template](https://github.com/hetzneronline/community-content/blob/master/tutorial-template.md).
