### ISSUE TITLE
Question concerning pfSense tutorial

### ISSUE THREAD

**Issue by nilskuhn** [hetzneronline/community-content#290]
Hi there,

I have a question concerning the [pfSense tutorial](https://community.hetzner.com/tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks):
In that tutorial, public access to the Web-UI for configuring pfSense firewall is disabled. Within the tutorial, that fact is stated as follows:
_The pfSense UI should not be reachable with the public IP address anymore._ 

I can't see why this should be a sensible setup?! With a long, cryptic admin password, the webui should be secure if publicly reachable. And what would be the proper way to configure pfSense, if its Web-UI is not reachable publicly?

Please let me know, if I misunderstood this point or what's the idea behind that setup.

Regards, Nils

**Comment by TomSDEVSN** [comment]
The idea behind this tutorial is that clients that should only be accessible within the private network, for example, should also only be able to configure the firewall.

An example:
You have set up an Active Directory infrastructure in the cloud and set up a pfSense as a firewall for these clients and servers. I don't think you want the web UI of your firewall to be accessible from outside then.

And even a long, cryptic password does not protect you from a security bug in the Web UI that could be abused.

**Comment by nilskuhn** [comment]
Ok, got it, thanks for clarification. 

But in case, I don't have an Active Directory infrasctructure behind and I want to use pfSense to secure some web services running on Hetzner Clouds internal network behind it, this setup doesn't make much sense, correct? Or would you operate the pfSense in this way nevertheless, connecting to web-ui via ssh tunneling or disable package filtering each time I want to edit some rules?

**Comment by rook59** [comment]
It's probably always better to allow access to the web interface only through some tunnel. If you don't absolutely need to expose an application, just don't do it.

**Comment by mhupfauer** [comment]
Additionally if all is lost you can re-enable the allow access to webui from wan rule via the hcloud console:
12 -> enableallowallwan 

[More recovery options](https://docs.netgate.com/pfsense/en/latest/troubleshooting/locked-out.html)
