### ISSUE TITLE
Disk decryption not working [How to install Ubuntu 20.04 with full disk encryption]

### ISSUE THREAD

**Issue by haupas** [hetzneronline/community-content#296]
This report is referencing https://github.com/hetzneronline/community-content/pull/293

First off, thanks for the tutorial! It is good to see that Hetzner is distributing tutorials that improve users privacy and promote encryption.

Sadly I experienced a problem while trying this out.
After creating a new Cloud Server and following the steps in the tutorial, the installimage script reports an error while processing the post-install.sh file. The following output is provided:
>update-initramfs: deferring update (trigger activated)
Dropbear has been added to the initramfs. Don't forget to check
your "ip=" kernel bootparameter to match your desired initramfs
ip configuration.
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for initramfs-tools (0.136ubuntu6.3) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-65-generic
/dev/mapper/control: open failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.167 (2019-11-30) and kernel driver (unknown version).
Command failed.
**INSTALLATION COMPLETE**
You can now reboot and log in to your new system with the
 same credentials that you used to log into the rescue system.

The debug log file seems fine and does not report any errors nor anything additional.

After restart, a login with the provided ssh key is possible, but entering the cmd `cryptroot-unlock` does nothing, no output nor error message. The excepted behavior would be to ask for the disk password.

The provided Step 4.1 with the command `update-initramfs -u` did not fix the problem.

Seems like there is a problem while installing the cryptsetup-initramfs and dropbear-initramfs package, which leads in the boot image not getting updated.

If this is not the correct place to report the problem, please delete the post and send me the correct contact address.
If requested I can provide a more detailed steps to reproduce this error and the output of the server console while booting.
After retrying multiple times with clean new cloud servers it seems like this tutorial is not working out-of-the-box with Ubuntu 20.04.

Thanks for looking into this.

**Comment by haupas** [comment]
Seems like the fix for this is mounting the /boot partition before calling the install of XY in the `post-install.sh`

**Comment by haupas** [comment]
Seems like the problem is the boot partition not being available for the post install script.
I fixed it with mounting the boot partition before calling `update-initramfs` from your fix in step 4.1 like this

```
mount /dev/mapper/luks-* /mnt/
chroot-prepare /mnt ; chroot /mnt
mount /dev/sda1 /boot
update-initramfs -u
```

This way the update of initramfs _actually does_ something, w/o mounting the boot partition the `update-initramfs` does not find anything in the /boot dir (as it's the empty one from the encrypted partition).

After restarting the command `cryptroot-unlock` is working and the decryption is successful.

So adding this to step 4.1 should fix it! 👍

**Comment by rook59** [comment]
@haupas do you want to submit a pull request with your fix?

**Comment by asciiprod** [comment]
This happened due to an oversight in installimage and has been resolved in 
https://github.com/hetzneronline/installimage/commit/215bc2c63a1dd3953a2b8d61ae1887cc94edd5a0
