### ISSUE TITLE
Use GitHub standards for contributing guidelines file

### ISSUE THREAD

**Issue by n-se** [hetzneronline/community-content#32]
We should consider using the standard for the contributing file in order to ensure that the contribution guidelines are at least somehow mentioned (and than hopefully read) if someone opens a new pull request.
https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

**Comment by leojakeson** [comment]
That's a good point.

Unfortunately, we have both an English and a German version of the contributing guidelines, and github doesn't mention anything about multiple languages.

We could rename the English version CONTRIBUTING.md and then the German version CONTRIBUTING.de.md to try and stick with our filename scheme.

**Comment by fdrechsler** [comment]
I think we should also add a
