### ISSUE TITLE
Missing default examples for IP addresses

### ISSUE THREAD

**Issue by n-se** [hetzneronline/community-content#34]
We already have default example IP addresses for the server, `10.0.0.1` and `2001:db8:1234::1`.

Following IP addresses are probably also needed for some tutorials:
- Gateway IPv4 and IPv6 (if someone wants to explain network configuration)
- NAT IPv4 and IPv6 (if someone wants to explain how to set up a virtual NAT with a bridge)
    - A good idea for v4 here would be `172.16.`
- Public client IPv4 and IPv6
    - A good idea for v4 here would be `192.168.`
- Private client IPv4 and IPv6

**Comment by Billito00** [comment]
According to https://tools.ietf.org/html/rfc5737 & https://tools.ietf.org/html/rfc3849 we recommend to use: 

IPv4 Address Blocks:
192.0.2.0/24
198.51.100.0/24
203.0.113.0/24

IPv6 Prefix:
2001:DB8::/32

######################
Server
v4: 192.0.2.1
v6: 2001:db8:1234::1

Gateway
v4: 192.0.2.254
v6: 2001:db8:1234::ffff

Public
v4: 203.0.113.1
v6: 2001:db8:5678::1

Private
v4: 198.51.100.1
v6: 2001:db8:9abc::1

**Comment by Perflyst** [comment]
> Server
So you want to replace 10.0.0.1?
