### ISSUE TITLE
Are changes/updates to existing tutorials accepted?

### ISSUE THREAD

**Issue by silviuvulcan** [hetzneronline/community-content#349]
More of a question than an issue but I wanted to know wether PRs to update existing tutorials are accepted ?

Case in point I recently setup a k8s cluster on Hetzner Cloud and following the tutorial [here](https://community.hetzner.com/tutorials/install-kubernetes-cluster) does not produce a working cluster - normal due to the highly dynamic nature of k8s.

I have my notes fresh so it would be easy for me to update/fix it. Should I go for a new tutorial targeting mentioning the current k8s version or should I update the existing one ?

Cheers!

**Comment by leojakeson** [comment]
Thanks for reaching out about this.

If your setup is appreciably different from the current tutorial, you're welcome to open a new tutorial. However, if it's really just about some updates/fixes to the current tutorial, then please open a PR for those updates. Either way you'll get a reward :)
