### ISSUE TITLE
Install a Kubernetes cluster on cloud servers

### ISSUE THREAD

**Issue by rseichter** [hetzneronline/community-content#367]
## Problem
The tutorial is outdated. Some of the Git paths for github.com/kubernetes are no longer available or refer to outdated versions of kubeadm/kubectl.

## Suggested Fix
Update tutorial to work with the latest stable Kubernetes version. At the time of creating this issue, that's Kubernetes v1.22.1.

**Comment by rook59** [comment]
There is already an open PR to update the tutorial: https://github.com/hetzneronline/community-content/pull/363
