### ISSUE TITLE
Install and Configure ONLYOFFICE Docs for Nextcloud

### ISSUE THREAD

**Issue by obsd-guru** [hetzneronline/community-content#369]
## Problem
An unexpected error occurred:
The JWS was signed by a public key the server does not support :: rpc error: code = Unknown desc = failed to select one blockedKeys: commands out of sync. Did you run multiple statements at once?

habe ein wenig gegoogelt, hat sich was an den letsencrypt installer etwas geändert?

## Suggested Fix

**Comment by rook59** [comment]
Let's Encrypt had an outage yesterday: https://letsencrypt.status.io/pages/incident/55957a99e800baa4470002da/613e5353f2cbd505371f0fc7
Can you please try again and let us know if the problem persists?
