### ISSUE TITLE
Proxmox doesn‘t Support mdraid

### ISSUE THREAD

**Issue by earlyXbirdNG** [hetzneronline/community-content#377]
The articel only describes how a mdraid would be created. This is not supported by proxmox because mdraid has no check for damaged blocks or sectors in the filesystem. ZFS has this possibility

**Comment by Billito00** [comment]
Could you please send us the link to the article you are talking about?

**Comment by earlyXbirdNG** [comment]
Sure 

https://pve.proxmox.com/wiki/Software_RAID

In the last section they are writing that mdraid is not supported.

https://community.hetzner.com/tutorials/install-and-configure-proxmox_ve/de

Here is mentioned: „ Nach Wunsch RAID-Level, Partitionierung und Hostnamen in der Konfiguration anpassen. Speichern und nach Abschluss der Installation neustarten.“

Your Script does Not Support ZFS.

**Comment by asciiprod** [comment]
We cannot add support for ZFS due to licensing issues. Our guide is intended to replicate the "Install Proxmox on Debian" guides also provided by Proxmox.
