### ISSUE TITLE
How-to: Install Fedora CoreOS at Hetzner Cloud

### ISSUE THREAD

**Issue by TonyBostonTB** [hetzneronline/community-content#390]
## Problem
glibc missing on rescue image

`coreos-installer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by coreos-installer)`

Installing FCOS doesn't work

`hcloud_server.master (remote-exec): E: Failed to fetch http://deb.debian.org/debian/pool/main/g/glibc/libc6-dbg_2.31-13_amd64.deb  404  Not Found [IP: 2a01:4ff:ff00::3:3 80]`

seems the coreos-installer is looking for the wrong glibc version

**Comment by rook59** [comment]
@Patrick-Remy can you please take a look?

Current debian 11.0 rescue:
```
root@rescue ~ # ls -la /lib/x86_64-linux-gnu/libc.so.6
lrwxrwxrwx 1 root root 12 Jul  6 21:16 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.31.so
root@rescue ~ # ls -la /lib/x86_64-linux-gnu/libc-2.31.so
-rwxr-xr-x 1 root root 1.8M Jul  6 21:16 /lib/x86_64-linux-gnu/libc-2.31.so

**Comment by Patrick-Remy** [comment]
Please see this issue, the howto is no longer working: https://github.com/Patrick-Remy/howto-fedora-coreos-hetzner-cloud/issues/1

It's a bit sad, that the only solution is to resize the VM down afterwards, but see this cleaner way: https://github.com/sedlund/terraform-hcloud-fcos

**Comment by rook59** [comment]
@Patrick-Remy thanks. Do you plan to contribute an update on your tutorial? Otherwise I'll check how we can handle this deprecation.

**Comment by Patrick-Remy** [comment]
I'm sorry, I do not plan to update it, the old documentation was already time intensive and I did setup my coreos server, but feel free to update my documentation to match the new approach, or probably @sedlund likes to migrate it?

**Comment by sedlund** [comment]
@rook59 it's easiest to install docker on the rescue and use the coreos-installer container to do the install.

@Patrick-Remy there is a bug in the way coreos-installer container udev interacts with the host systsem udev on single core machines.  But I found bind mounting the system udevadm to the container resolves it so you don't have to resize down the vm any longer.  See:  https://github.com/coreos/coreos-installer/issues/575#issuecomment-885287221

**Comment by svenja11** [comment]
Closing because the tutorial works again.
See #727
