### ISSUE TITLE
How to install MikroTik CHR on Hetzner Cloud

### ISSUE THREAD

**Issue by ArtemDubchikov** [hetzneronline/community-content#394]
Hi!
https://community.hetzner.com/tutorials/mikrotik-chr-basic-setup
After applying this instruction and restarting the VPS, an error is displayed. Technical support replies that it does not deal with such issues. There is no point in using the VSP without an answer to this problem. 
![image](https://user-images.githubusercontent.com/79627275/144007955-51c95a24-d0a1-4162-9e8d-e16b9bdc6564.png)

**Booting from Hard Disk...
Loading system with initrd
ERROR: could not find disk!
Please attach it somewhere else.**

**Comment by rook59** [comment]
I can't reproduce your issue. It works without any issues:
```
curl -L https://download.mikrotik.com/routeros/6.47.9/chr-6.47.9.img.zip > mikrotik-chr.zip
funzip mikrotik-chr.zip > mikrotik-chr.img
dd if=mikrotik-chr.img of=/dev/sda bs=1M
reboot
```

![image](https://user-images.githubusercontent.com/34218225/144014872-66322f87-1fcf-4213-833c-97519b76beaf.png)

**Comment by ArtemDubchikov** [comment]
MikroTik CHR is not working on Hetzner Cloud in my setup

**_curl -L https://download.mikrotik.com/routeros/6.47.9/chr-6.47.9.img.zip > mikrotik-chr.zip
funzip mikrotik-chr.zip > mikrotik-chr.img
dd if=mikrotik-chr.img of=/dev/sda bs=1M
reboot_**

**Comment by christer88** [comment]
Good afternoon,

I present the same problem, I cannot upload the CHR, in the following location 

![image](https://user-images.githubusercontent.com/50426201/146659278-6900c643-a0af-44b3-8a73-3d4e44c32fcd.png)

![image](https://user-images.githubusercontent.com/50426201/146659230-b77e7d42-ea60-426d-a49c-95f21ab691a7.png)

![image](https://user-images.githubusercontent.com/50426201/146659258-19c31b9e-1ade-48d9-8bb8-6c66c3f91348.png)

apparently it is only on the server hosted in the USA, I ran a test on the one from Finland and I had no problem running CHR
