### ISSUE TITLE
How to install an encrypted ubuntu20.04 with automated unlocking via tang and clevis

### ISSUE THREAD

**Issue by quorak** [hetzneronline/community-content#395]
## Question
Is there a way to enable private networks for these instances?
I know it is explicitly excluded, just wondering about the effort, or even possible?
thanks you so much!

**Comment by rook59** [comment]
@asciiprod can you say something about this?

**Comment by asciiprod** [comment]
It works the same way. There is nothing special. Please see:
https://docs.hetzner.com/cloud/networks/server-configuration
