### ISSUE TITLE
Proxmox on Hetzner Cloud

### ISSUE THREAD

**Issue by lonesomewalker** [hetzneronline/community-content#401]
## Problem
totally useless, please describe at least ONE realistic scenario.
## Suggested Fix
delete this totally nonsense "tutorial".

**Comment by rook59** [comment]
Use case is described in the tutorial:

> Even if we can´t (till now) use KVM, as nesting is not supported/enabled, we can still benefit using LXC containers.

**Comment by lonesomewalker** [comment]
Would you like to explain HOW to benefit from this?
No, because you just waste time.
