### ISSUE TITLE
How to set up K3S, GlusterFS and Hetzner's cloud load balancer

### ISSUE THREAD

**Issue by DrZoidberg09** [hetzneronline/community-content#405]
## Problem
First of all, thank you so much for providing the tutorial!
I am completely new to Kubernetes and K3s and followed the tutorial 1 by 1 (even 3 times) to rebuild your setup.
However, I just don't get it working. Everything works fine until the point of accessing the test web server.
The load balancer never gets into the healthy state and hence the website is not accessible.

To be honest, I don't even know how to debug and see why the k3s cluster cannot properly talk to the load balancer.

Any suggestions are highly appreciated. Thank you so much!

**Comment by Billito00** [comment]
@virtualzone can you help with this issue?

**Comment by svenja11** [comment]
I know it might be a little bit too late for you @DrZoidberg09, but in case others also run into a similar issue:

I have checked the tutorial and it should work just fine.

Without knowing any other details, I would suggest:

- **Double-check the network**
  
  Make sure your Load Balancer and your nodes are in the same network and you’re using the correct name. In this tutorial, `network-kubernetes` is used as an example name for the network. If your network has a different name, make sure to replace it in **all** commands.

- **Double-check the service**
  
  If you didn't add an SSL certificate, make sure you're using the correct service (`http:80 → 80`).

- **Double-check the Traefik ingress route**
  
  In step 7.2, make sure to replace `<example.com>` with your own URL or IP. The rest is just copy&paste, so it might be easy to miss.

Also note that the entire tutorial exclusively uses private IP addresses and not public IPs.
