### ISSUE TITLE
Install and Configure Ubuntu Remote Desktop with XFCE using X2Go

### ISSUE THREAD

**Issue by gowebua** [hetzneronline/community-content#414]
## Problem
Finally on our server, we remove root´s password. The new created user has got sudo rights.
passwd -d root
## Suggested Fix

New user doesn't have sudo rights. After this you can not login to the server is root.

**Comment by yasergirit** [comment]
I have same problem. After created user holu I cannot connect server as root and created user has no sudo rights.

But related content is different.

**Comment by svenja11** [comment]
Fixed in #661
