### ISSUE TITLE
Proxmox VE Installieren und Konfigurieren

### ISSUE THREAD

**Issue by Yalu64** [hetzneronline/community-content#415]
## Problem

When following the tutorial on the website it will always break the apt-get update command, due to proxmox thinking the enterprise version is installed and trying to update using the enterprise version, which does not work as the IP is not whitelisted.
![image](https://user-images.githubusercontent.com/56490576/149677344-c19f7345-da79-4f9e-afb0-905eaa748127.png)

## Suggested Fix

By adding another step to the tutorial this issue can easily be fixed.

1. nano /etc/apt/sources.list.d/pve-enterprise.list

2. Adding a #
![image](https://user-images.githubusercontent.com/56490576/149677393-d3fe4e64-8c7d-4158-80a6-03c25837ad4e.png)

3.  Fixed
![image](https://user-images.githubusercontent.com/56490576/149677405-69051091-23ff-4b57-9f06-186d5a37af8f.png)

**Comment by rook59** [comment]
Not really an issue, just doesn't look "nice". apt-get update still works even if some repos are not accessible

**Comment by Yalu64** [comment]
> Not really an issue, just doesn't look "nice". apt-get update still works even if some repos are not accessible

Yes that is completely right, but about 2 weeks ago it actually caused some packages to break somehow. I am not sure how but after commenting out the pve-enterprise it fixed this issue. Might be more than just a cosmetic issue.
