### ISSUE TITLE
Install and Configure BorgBackup

### ISSUE THREAD

**Issue by fauust** [hetzneronline/community-content#422]
## Problem
Typo

## Suggested Fix
```diff
- Since BorgBackup uses duplication, you can make backups very quickly and without using much storage.
+ Since BorgBackup uses deduplication, you can make backups very quickly and without using much storage.
```

Also, you can achieve the same with another very popular backup tool ([restic](https://restic.readthedocs.io/en/stable/)). You may want to give it as a tip in this documentation.

Cheers!

**Comment by jasonnab** [comment]
I have opened a pull request for two other small typos here. I was unsure if I should open an issue, or a pull request for typos.
https://github.com/hetzneronline/community-content/pull/426
