### ISSUE TITLE
Einrichten eines Let's Encrypt Zertifikats auf Cloud Load Balancern mit externer Domain

### ISSUE THREAD

**Issue by NullP0interEx** [hetzneronline/community-content#431]
## Problem

Im Screenshot mit den DNS Einträgen sind die Punkte am Ende des Nameservers nicht zu sehen, weshalb ich es falsch eingerichtet habe. Es wäre schön, wenn Sie dies für folgende Kunden in der englischen und deutschen Fassung korrigieren würden.

## Suggested Fix

**Comment by NullP0interEx** [comment]
![CleanShot 2022-03-08 at 18 03 22@2x](https://user-images.githubusercontent.com/8757449/157288173-8b8e60c7-ba45-402c-ada2-480b9ed8ce73.png)

**Comment by Billito00** [comment]
@BackInBash Can you look at the issue and update if necessary.

**Comment by BackInBash** [comment]
Ich sehe da um ehrlich zu sein keinen Verbesserungsbedarf.
Wenn man den Screenshot nicht aus dem Kontext reisen würde sieht man, dass direkt darüber eine RFC konforme Implementierung des Records abgebildet ist.

![Screen Shot 2022-05-02 at 13 08 20](https://user-images.githubusercontent.com/48181660/166224761-61db81ec-5743-4682-8ef4-b0e408fec2dd.png)

Und wenn der DNS Anbieter eine RFC konforme Eingabe fordert (CloudFlare tut dies nicht), muss diese richtig umgesetzt werden.
https://www.ietf.org/rfc/rfc1035.txt
