### ISSUE TITLE
Reward questions

### ISSUE THREAD

**Issue by SyscoreV1** [hetzneronline/community-content#432]
"For every tutorial we publish on Hetzner Online Community, we will give up to €50 in credit on your account!"
 Does it mean up to total i can get? or per publish?

if i published and got accepted 5 articles, will i receive $250 or $50?
Also does each article count as a fixed $50 or can be up to $50 or nothing?

**Comment by leojakeson** [comment]
The credit is per tutorial. So if we publish 5 of your tutorials, you can get up to €250.

We give *up to* €50 credit per tutorial. The amount depends on a few factors (like length and thoroughness). We've never published anything without providing credit.
