### ISSUE TITLE
Bad practices on "How to create a Minecraft server on a VPS"

### ISSUE THREAD

**Issue by Cubxity** [hetzneronline/community-content#434]
[Original comment on Twitter](https://twitter.com/cubxity/status/1504422514981847043) 

Tutorial PR: #429 

### 1. Third party download API

The tutorial uses a third-party download API (serverjars.com), which is run by Songoda. Songoda is known to produce poor quality plugins for Minecraft, which makes them less reputable.

Furthermore, serverjars redistributes Vanilla Minecraft server JAR, which may go against the Minecraft EULA.

Both Minecraft and Paper provide first-party downloads. 
- https://www.minecraft.net/en-us/download/server
- https://papermc.io/downloads

### 2. Unoptimized JVM startup flags

JVM startup flags are crucial for Minecraft servers. By not having the appropriate flags, your server may not perform at it's fullest potential.

See https://docs.papermc.io/paper/aikars-flags#recommended-jvm-startup-flags

**Comment by rook59** [comment]
> https://www.minecraft.net/en-us/download/server

minecraft.net does not provide links to older server.jars though. Is there any alternative API to get old server jars?

cc @YusufYaser

**Comment by Cubxity** [comment]
> > https://www.minecraft.net/en-us/download/server
> 
> minecraft.net does not provide links to older server.jars though. Is there any alternative API to get old server jars?
> 
> cc @YusufYaser

Yes, see:
- https://launchermeta.mojang.com/mc/game/version_manifest.json
- https://wiki.vg/Game_files

**Comment by Cubxity** [comment]
> @YusufYaser can you adapt this and also add a hint to the recommended and probably helpful server flags mentioned above?

In my opinion, the flags should be in the script by default. Since there's no reason to not do so.
