### ISSUE TITLE
How to set up K3S, GlusterFS and Hetzner's cloud load balancer

### ISSUE THREAD

**Issue by andruwa13** [hetzneronline/community-content#439]
## Problem
does not define the real IP

X-Forwarded-For: [10.244.2.2]
X-Real-Ip: [10.244.2.2]

## Suggested Fix

**Comment by nickkrykunov** [comment]
Same
Any suggestions?

**Comment by svenja11** [comment]
I know this is a late response but in case others run into a similar issue:

I have updated the tutorial (see #699). It now includes this section:


> If you need the real IP, you can use this configuration instead:
> 
> ```bash
> cat <<EOF > /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
> apiVersion: helm.cattle.io/v1
> kind: HelmChartConfig
> metadata:
>   name: traefik
>   namespace: kube-system
> spec:
>   valuesContent: |-
>     additionalArguments:
>       - "--entryPoints.web.proxyProtocol.trustedIPs=0.0.0.0/0"
> EOF
> ```
> 
> Make sure the service of your Load Balancer has "Proxy protocol" enabled.

I hope this helps.
