### ISSUE TITLE
Proxmox VE Installieren und Konfigurieren

### ISSUE THREAD

**Issue by mr2017x** [hetzneronline/community-content#456]
## Problem

Netzwerkkonfiguration warum Definition Bridged, Definition Routed, dann wieder Bridged dann wieder routet, klare Herausstellung welche Option 

## Suggested Fix

klare Herausstellung welche Option wann benötigt wird, gf. auch mit example Adressen und Struktur Bridged host, bridged vm dann routed usw.

**Comment by biberairport** [comment]
Thank you for the suggestion, the article has been improved but only in English language currently. We will make some changes to the german article soon.
