### ISSUE TITLE
Install and configure AWX without using Kubernetes

### ISSUE THREAD

**Issue by NiclasPe** [hetzneronline/community-content#460]
#### Step 2.5.1
```
make docker-auth awx/projects docker-compose-sources
```
#### Returns: 
`make: *** No rule to make target 'docker-auth'.  Stop.`

#### Step 2.5.2 - Generating UI files
```
docker-compose -f tools/docker-compose/_sources/docker-compose.yml run --rm awx_1 make clean-ui ui-devel
```
#### Returns:
`ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './tools/docker-compose/_sources/docker-compose.yml'`

## Suggested Fix
There are some deleted files in the new 21.0.0 Version of AWX. At the Moment i haven´t an fix

**Comment by danielpotthast** [comment]
See #388 .

You need to run `make awx/projects docker-compose-sources` at step 2.5.1 – it’s working for me (running v21.1.0)
