### ISSUE TITLE
Installing Proxmox and Docker on ZFS

### ISSUE THREAD

**Issue by bari86** [hetzneronline/community-content#463]
## Problem
On the line:
For additional IPs, the following bridge configuration can be used:

`auto vmbr1
iface vmbr1 inet static
        address <10.0.0.1> # Replace <10.0.0.1> with the main IP
        netmask 255.255.255.255
        bridge_ports none
        bridge_stp off
        bridge_fd 0
        up ip route add <additional ip 1>/32 dev vmbr0
        up ip route add <additional ip 2>/32 dev vmbr0`

The last two lines, is it vmbr0 or vmbr1? I used vmbr0 and when I create VM, if I set it to vmbr0 I can get internet on that VM, but if I set it to vmbr1, there is no internet. 

Update: 

## Suggested Fix
Just double-check the last two lines and change if needed to vmbr1.

Update: there is a few typo there, but for the vmbr, its would be the opposite of that you written before.

**Comment by Billito00** [comment]
@Kenzim Could you please check this issue.

**Comment by Kenzim** [comment]
This is correct, this is for a routed configuration with additional IPs. It does not matter what IP you assign on vmbr1 - this becomes the gateway inside the vm. However now that the hypervisor is the router, you need to give it routes. Vmbr0 is bonded to the externel network nic, so you tell it that the additional ips should be routed there, as in `up ip route add (additional ip)/32 dev vmbr0`
The same configuration works with additional subnets, just change the cidr to the appropriate value when adding the route

**Comment by Kenzim** [comment]
@bari86 @Billito00  Is there any more confusion on this?

**Comment by biberairport** [comment]
No further questions asked, we will close this now.
