### ISSUE TITLE
Install and Configure BorgBackup: unclear text

### ISSUE THREAD

**Issue by Maltimore** [hetzneronline/community-content#464]
## Problem The following text is unclear to me:

"For Borg to be enabled on your storage box, you must first enable the service on the Robot webinterface. To do this, go to the settings page of your storage box in Robot and click on activate in "SSH support".

Since SSH is not available on the storage box, you must use SFTP or something similar for this step."

Two problems:
1. It says the first thing to do is to enable SSH support in the web interface. Then in the third sentence it says that "since SSH is not available..". I thought we just enabled it in step 1.
2. Then again, it says "Since SSH is not available on the storage box, you must use SFTP or something similar for this step.". Is this still about the ssh enabling? I thought we just did that via the web interface? But if it's via the webinterface, what do we need SFTP for?

## Suggested Fix

**Comment by leojakeson** [comment]
Thanks for pointing this out, we're working on rewriting this section to make it more clear.
