### ISSUE TITLE
Setting up a Let's Encrypt certificate on cloud load balancers with external domain

### ISSUE THREAD

**Issue by adrijanb** [hetzneronline/community-content#487]
## Problem
not working anymore. Cloudflare is setting up an own _acme-challenge which is not visble 

## Suggested Fix

**Comment by svenja11** [comment]
@BackInBash Can you take a look at this?
Would you be interested in providing an update to [your tutorial](https://github.com/hetzneronline/community-content/blob/master/tutorials/configure-lb-cert-with-external-domain/01.en.md)? #509 might also be relevant.

**Comment by BackInBash** [comment]
I don't get the problem here. Just use a SubDomain for delegation and you are good to go.
And if you need to root domain you should probably think about migrating completely from cloudflare to hetzner DNS.

**Comment by svenja11** [comment]
Closing because of comment above.
