### ISSUE TITLE
Install and Configure BorgBackup -  Changing Borg config on Storage Box not possible. "Repository must be local"

### ISSUE THREAD

**Issue by FelixSab** [hetzneronline/community-content#493]
## Problem

https://community.hetzner.com/tutorials/install-and-configure-borgbackup

I am trying to run the following command remotely, but borg is denying me that with the error message "Repository must be local". The issue is that the provided pseudo-shell in the Storage Box does not provide me with a way to change the borg config locally (or it isn't documented).

`borg config ssh://uXX@uXX.your-storagebox.de:23/./backups/server1 additional_free_space 2G`

## Suggested Fix

Add documentation for updating the borg config

**Comment by Exoou** [comment]
https://github.com/borgbackup/borg/issues/5252
what about if you access your storagebox with SFTP and change config manually? I don't know if that works, never tried, but you can access storagebox with SFTP and download/upload files and config file should be on your folder ./backups/server1
