### ISSUE TITLE
Block Outgoing Traffic to Private Networks

### ISSUE THREAD

**Issue by EvilOlaf** [hetzneronline/community-content#502]
## Problem
The solution does not work when using containers/virtualization with routing like LXD because their traffic will never reach the OUTGOING netfilter table as it passes through FORWARDING.

## Suggested Fix
As I described that issue at Linuxcontainers discussion platform (https://discuss.linuxcontainers.org/t/prevent-routing-of-private-network-to-public/15275) the suggested fix was to null-route private/reserved IP ranges to catch packets with bad destination before they leave the system. As *tomb* states this should not affect existing routes, like used by the LXD bridge, and with a quick test I could confirm that.

Full list of private/reserved/special purpose ranges that *shall not pass*:
```
ip route add unreachable 10.0.0.0/8
ip route add unreachable 100.64.0.0/10
ip route add unreachable 192.168.0.0/16
ip route add unreachable 172.16.0.0/12
ip route add unreachable 169.254.0.0/16
ip route add unreachable 192.0.0.0/24
ip route add unreachable 192.0.2.0/24
ip route add unreachable 192.88.99.0/24
ip route add unreachable 198.18.0.0/15
ip route add unreachable 198.51.100.0/24
ip route add unreachable 203.0.113.0/24
ip route add unreachable 224.0.0.0/4
ip route add unreachable 240.0.0.0/4
```

**Comment by svenja11** [comment]
Thank you for pointing that out!
