### ISSUE TITLE
Setting up a Let's Encrypt certificate on cloud load balancers with external domain

### ISSUE THREAD

**Issue by SamuelMTDavies** [hetzneronline/community-content#509]
## Problem
Doesn't seem to work when setting up with AWS Route53. Continually errors out on the certificate generation.

## Suggested Improvement
How to set this up with a subdomain when the root domain is hosted elsewhere.

**Comment by svenja11** [comment]
Thank you for your suggestion. Please see [the comment](https://github.com/hetzneronline/community-content/issues/487#issuecomment-1586986411) in the linked issue and please also note the following information from [docs.hetzner.com](https://docs.hetzner.com/cloud/load-balancers/faq):

> [How can I manage my certificates?](https://docs.hetzner.com/cloud/load-balancers/faq#how-can-i-manage-my-certificates)
> 
> * Create certificate: The domain name must be **managed through Hetzner DNS**.
