### ISSUE TITLE
Install and configure a Router VM for VMware vSphere

### ISSUE THREAD

**Issue by soukron** [hetzneronline/community-content#511]
## Problem
This article explains how to create a new PortGroup attached to a vSwitch which has a NIC as uplink, therefore even if the virtual machines don't have an external IP and the traffic is routed, the MAC is exposed in the NIC and the security scans of Hetzner detect unauthorized MAC addresses.

## Suggested Fix
Not sure how to fix it. 
Create a new vSwitch without uplink could be a solution but ESX/vSphere rejects to attach virtual machines to that kind of networks.

**Comment by biberairport** [comment]
The router VM should not communicate with the uplink if local IP addresses are used. We are not aware that this tutorial as it stands are causing any MAC address problems. Public IP addresss are routed to the respective VM. The router VM has two NICs where one is part of the bridge to the additional single IP and the other one is part of the routed network where the VMs get the IPs, so I may be wrong here but I don't see how the VMs are going to cause trouble here. Maybe we test more thoroughly and expane the description in future. Thank you for the report anyway :)

**Comment by soukron** [comment]
>> We are not aware that this tutorial as it stands are causing any MAC address problems 
>> so I may be wrong here but I don't see how the VMs are going to cause trouble here.

Well, I am reporting it because I suffered the issues :) Therefore you're aware but you don't believe me.

**Comment by biberairport** [comment]
I will try this out as soon as possible, so you had this issue while having VMs with a local IP only?

**Comment by soukron** [comment]
Correct. The VMs have only a local IP but they're attached to the same vSwitch, therefore the L2 traffic is forwarded to the Hetzner network and their monitoring systems detect unknown MAC addresses and you get a report.

My solution was, if I'm not wrong at this moment (because it was time ago when I submitted the issue), to create a Hetzner vSwitch and attach the physical NIC to it so it provides another layer to filter the L2 traffic as it has a VLAN ID.

**Comment by soukron** [comment]
Okay, I gave it another try to the tutorial and it worked. For some reason this time it allowed me to attach the VMs to a vSwitch without any uplink interface.

Feel free to close it!
