### ISSUE TITLE
Question about updating old article with a specific OS version in folder name

### ISSUE THREAD

**Issue by AlexandrBoltris** [hetzneronline/community-content#516]
I want to update article [Install and Secure Nginx with Let's Encrypt in Debian 10](https://community.hetzner.com/tutorials/install-and-secure-nginx-lets-encrypt-debian-10) from `Debian 10` to `Debian 11`.

Since the OS version is a part of folder name (as well as URL), I don't best way to deal with folder name. After a small research I can offer the following options:

* remove `10` from folder name and write text `This tutorial has been tested on Debian 10 and 11` into the article
* create a new acticle in `...debian-11` folder

@leojakeson WDYT?

**Comment by Billito00** [comment]
@AlexandrBoltris It's best if you create a new article and additionally point out in the old tutorial that there is a newer version of it.

**Comment by AlexandrBoltris** [comment]
@Billito00 thank you for the asnwer.
