### ISSUE TITLE
Install Rancher on a Cloud Server (Single Node)

### ISSUE THREAD

**Issue by fatih-akin** [hetzneronline/community-content#543]
I am getting error below. So rancher can not download from  [https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js ](url) GCP

`<Error>`
`<Code>UserProjectAccountProblem</Code>`
`<Message>The project to be billed is associated with a closed billing account.</Message>`
`<Details>The billing account for the owning project is disabled in state closed</Details>`
`</Error>`

**Comment by zmbcgn** [comment]
Seems like a temporary problem with the Google account. As of today, the link is working.

**Comment by zmbcgn** [comment]
Duplicate of #538 .

**Comment by biberairport** [comment]
Thank you for the report, since it was a temporary problem we will close this now.
