### ISSUE TITLE
Install and Configure Plex Media Server on CentOS 8

### ISSUE THREAD

**Issue by igrschmidt** [hetzneronline/community-content#547]
## Problem
There's a type on the text of step 2

Step 2 - Firewall Configuration (Optional)
To be able to access the **Plesk Media Server** over the Internet we need to configure our server to allow connections on some ports.

## Suggested Fix
Fix to "Plex Media Server"

**Comment by svenja11** [comment]
Thank you for pointing that out! The typo is now fixed. (#551)
