### ISSUE TITLE
How to monitor Hetnzer Ubuntu VM

### ISSUE THREAD

**Issue by MohdRashid01** [hetzneronline/community-content#548]
My 4 VMs are running in Hetzner Cloud

I have monitor 4 VMs of ubuntu OS running on it and some data is also running in all 4 VMs.

I want to write a shell script on that 4 VMs whether they are Up/Down like ping

That script should check daily or every hour about 4 VMs is Up/Down or Not

Please give me some link or tips how can i write it

and Shell script i will keep in jenkins job to daily it will check

**Comment by biberairport** [comment]
You may find scripts for monitoring on github: https://github.com/topics/monitoring-scripts?l=shell
If you need to go more in depth you may use tools like Prometheus for example: https://community.hetzner.com/tutorials/install-and-configure-prometheus-stack
