### ISSUE TITLE
High CPU Usage in Ubuntu Hetzner VM

### ISSUE THREAD

**Issue by MohdRashid01** [hetzneronline/community-content#549]
Due to high usage of CPU in ubuntu vm it become unresponsive cannot login into VM and we have to restart direct through hetnzer stop and start option

Below is the screenshot which i capture and i dont know where is that file coming and why it usage is high any help would be great

./sdjdshdgdsdsfsfausjashsaggsafsfaa.x86 

Even i try everything to locate,search and find the file but didnt get it 
![image](https://user-images.githubusercontent.com/7812871/215181803-0c6bf68d-4a65-4f0c-a789-d3bd31cf1df8.png)

**Comment by biberairport** [comment]
If you don't know what it is, it's probably malware. We recommend saving your data and reinstall and open a ticket via the Hetzner Robot for further assistance. This repo is only for our community content.
