### ISSUE TITLE
How to install Debian 11 encrypted with LVM on a NVMe software RAID

### ISSUE THREAD

**Issue by quorak** [hetzneronline/community-content#556]
## Problem
Thanks for the great tutorial
I tried use the tutorial with a ipv6 only server.
Unfortunately after reboot I cannot connect anymore. The ssh times out.

## Suggested Fix
cannot help here

**Comment by makorne** [comment]
The same with ipv4 and additional disks.

And kvm shows no Debian in grub at all.
Only old AlmaLinux in grub menu.

![Alma_Screenshot_2023-04-08_14-00-23](https://user-images.githubusercontent.com/26540498/230751858-a80c2fb1-804d-4c2b-903b-0c56fcd39bd1.png)

**Comment by svenja11** [comment]
Hello @quorak,
I'm sorry for the late response. Unfortunately, this tutorial does not work with IPv6-only servers. For this tutorial to work properly, you would have to add an IPv4 address to your server.
