### ISSUE TITLE
How to route cloud server over private network using pfSense and Hetzner Cloud Networks: default route is not automatically added to machine

### ISSUE THREAD

**Issue by perlun** [hetzneronline/community-content#561]
## Problem
Default route is not automatically added to machine

## Details
I've created a new default route to try and get traffic routed via my custom router inside the private network like this:

```
$ hcloud network add-route hetzner-cloud-ci-network --destination 0.0.0.0/0 --gateway 172.22.16.2
700ms [==================================] 100.00%
Route added to network 2552954
```

However, I don't get any "special" default route set up on the machine despite this. :thinking: Do you have to take any manual step to make this happen? (I've struggled trying to get this done via command line but it has been challenging, which I why I hoped that the automatic provisioning done via `hcloud`/`hc-utils` would be of use.

I've tried detaching/re-attaching the machine as well, but it hasn't helped. Do I have to handle this manually and if so, do you have any suggestions on how to successfully route all traffic via a particular gateway (which in turn needs to be routed via 172.22.16.1 because of the Hetzner setup).

Big thanks in advance!

```
root@some-host:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.31.1.1      0.0.0.0         UG    100    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.22.16.0     172.22.16.1     255.255.255.0   UG    0      0        0 ens10
172.22.16.1     0.0.0.0         255.255.255.255 UH    0      0        0 ens10
172.31.1.1      0.0.0.0         255.255.255.255 UH    100    0        0 eth0
185.12.64.1     172.31.1.1      255.255.255.255 UGH   100    0        0 eth0
185.12.64.2     172.31.1.1      255.255.255.255 UGH   100    0        0 eth0
```

## Suggested Fix
N/A

**Comment by svenja11** [comment]
Hello @perlun 🙂

For cloud servers in a Hetzner Cloud Network, Hetzner only adds one additional route on the servers. This route is used to route destination IPs that are within the same private Network.

If you want to route destination IPs that are outside of the private Network, you will have to manually add an addional route on your cloud servers (see "[What is special about route destinations that are not part of my network IP range?](https://docs.hetzner.com/cloud/networks/faq#what-is-special-about-route-destinations-that-are-not-part-of-my-network-ip-range)")

In the tutorial you referred to, this is done in the step "[Configure route for private networking](https://community.hetzner.com/tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks#configure-route-for-private-networking)". Before this step, `ip l` is used to get the relevant private Network interface.

**Comment by perlun** [comment]
Thanks a lot for the answer @svenja11. Thanks to it, I finally figured it out now. :pray: Much appreciated!

1. The route needs to be present in the Hetzner UI/added via `hcloud`. Something like this:

   ![image](https://user-images.githubusercontent.com/630613/221142910-76ba3d66-b745-455d-bcc3-89ec026c1fc4.png)

2. With this in place, add a default route as suggested in the guide (`ip route add default via 172.22.16.1`). Hetzners router will then use the configured information (the default route above) and pass the traffic along to the 172.22.16.2 machine.

For me with a slightly "I want to understand how it works" personality, I think it was this extra information on how it all fit together that was missing. I was wrestling with trying to route the traffic via 172.22.16.2 directly, and didn't understand that the Hetzner router would be "aware" of these routes being set up and use it to route the traffic to the right place. I guess the guide could be slightly modified to make this clearer, if you want to. :+1: Either way, I hope this issue can also be of help to others who are struggling with similar issues.
