### ISSUE TITLE
Repairing LVM Volumes incomplete

### ISSUE THREAD

**Issue by Joshi425** [hetzneronline/community-content#58]
The Tutorial for [Repairing LVM Volumes](https://community.hetzner.com/tutorials/repairing-lvm-volumes/01.en) is in my eyes incomplete: 

- no searching for the cause of filesystem errors 
- no checking if a disk has errors 
- no warning to continue only if you have a backup
- there should be a basic rundown of mdadm RAIDs to understand what you are doing

there are tons of good fsck Tutorials out there, having this incomplete one under Author Hetzner Online isn't good.

**Comment by leojakeson** [comment]
Good point. Being reverted #28
