### ISSUE TITLE
Install a Kubernetes cluster on cloud servers

### ISSUE THREAD

**Issue by mahdi-04** [hetzneronline/community-content#581]
## Problem
I have this issue in installation csi-driver.

root@master-1:~# kubectl apply -f https://raw.githubusercontent.com/kubernetes/csi-api/release-1.14/pkg/crd/manifests/csidriver.yaml
error: resource mapping not found for name: "csidrivers.csi.storage.k8s.io" namespace: "" from "https://raw.githubusercontent.com/kubernetes/csi-api/release-1.14/pkg/crd/manifests/csidriver.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
## Suggested Fix
> kubectl apply -f https://raw.githubusercontent.com/kubernetes-retired/csi-api/master/pkg/crd/manifests/csidriver.yaml
> kubectl apply -f https://raw.githubusercontent.com/kubernetes-retired/csi-api/master/pkg/crd/manifests/csinodeinfo.yaml
> kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/main/deploy/kubernetes/hcloud-csi.yml

**Comment by svenja11** [comment]
Thank you for pointing this out! 🙂
