### ISSUE TITLE
Grundlegende Cloud-Konfiguration

### ISSUE THREAD

**Issue by ToM-Korn** [hetzneronline/community-content#592]
## Problem
Grundlegend gute Beschreibung aber die Cloudconfig hat für mich in dieser Form nicht funktioniert. 

Ich habe meinen user angegeben und meinen ssh key aber nach dem server boot hat der server sowohl bei meinem user als auch bei root ein passwort verlangt.... da der root user deaktiviert ist gab es keine moeglichkeit mich anzumelden.... 

`#cloud-config
users:
  - name: demo
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv60WjxoM39LgPDbiW7ne3gu18q0NIVv0RE6rDLNal1quXZ3nqAlANpl5qmhDQ+GS/sOtygSG4/9aiOA4vXO54k1mHWL2irjuB9XbXr00+44vSd2q/vtXdGXhdSMTf4/XK17fjKSG/9y3yD6nml6q9XgQxx9Vf/IkaKdlK0hbC1ds0+8h83PTb9dF3L7hf3Ch/ghvj5++tWJFdFeG+VI7EDuKNA4zL8C5FdYYWFA88YAmM8ndjA5qCjZXIIeZvZ/z9Kpy6DL0QZ8T3NsxRKapEU3nyiIuEAmn8fbnosWcsovw0IS1Hz6HsjYo4bu/gA82LWt3sdRUBZ/7ZsVD3ELip user@example.com`

## Suggested Fix

**Comment by ToM-Korn** [comment]
PS: Ich lösche und setzte den Server jetzt das 4 mal... ohne cloud config und mach das schritt fuer schritt manuell ... da hab ich kontrolle drueber was  passiert.

**Comment by ToM-Korn** [comment]
sorry ... hab einen fehler uebersehen den ich gemacht habe. wahrscheinlich lag es daran.

habe vergessen in der letzten zeile den "AllowUsers holu" auf meinen zu ändern.

ich probier es dann das naechste mal noch mal

**Comment by svenja11** [comment]
Hallo @ToM-Korn,
hat der neue Versuch mit dem eigenen Benutzer anstelle von `holu` funktioniert? Dann würde ich dieses Issue schließen.
