### ISSUE TITLE
Install and configure borgmatic

### ISSUE THREAD

**Issue by commodis** [hetzneronline/community-content#600]
First thanks for the very concise tutorial!

https://community.hetzner.com/tutorials/install-and-configure-borgmatic

## Problem

When I installed `borgmatic` the suggested services and timers were already installed.

## Suggested Fix

I am not sure if it depends on the `borgmatic` version or the distro, but it might be noted, that `Step 2` was optional for me.
It might have even collided because two backups would be been run using your example.

I just tried the installation on a Ubuntu 20.04 installation and the service and timer were not automatically installed.

**Comment by svenja11** [comment]
Thank you @commodis for pointing that out!
