### ISSUE TITLE
Install and Configure BorgBackup

### ISSUE THREAD

**Issue by jenslink** [hetzneronline/community-content#606]
## Problem

At least for me the following command is displayed as two lines which lead me to believe that there is some kind 
of white space between the first part and `/./backups/server1`

```
$ borg init --encryption=repokey ssh://u123456@u123456.your-storagebox.de:23
/./backups/server1
```

## Suggested Fix

No idea how to fix this, maybe just add a comment. Or maybe add one of those 
copy "buttons" to the code block on the site.

**Comment by svenja11** [comment]
Thank you @jenslink for pointing this out! I have updated the way it is formatted.
