### ISSUE TITLE
How to route cloud server over private network using pfSense and Hetzner Cloud Networks

### ISSUE THREAD

**Issue by natenjo** [hetzneronline/community-content#615]
In the article https://community.hetzner.com/tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks , in the section

> Go to System ➔ Routing ➔ Static Routes
> 
> Create a new route:
> 
> Destination network: 10.0.0.0/16
> Gateway: WAN_DHCP - 172.31.1.1
> Description: Make private network reachable for pfSense
> Save and apply the changes.

the gateway has to be LAN_DHCP - 10.0.0.1 instead of WAN_DHCP - 172.31.1.1

Later on in the article, when setting up the client, the correct setting was chosen:

>  (post-up ip route add default via 10.0.0.1)

If this is not done, the client can reach pfsense, but but the other way round.

**Comment by svenja11** [comment]
Thank you for pointing this out!
