### ISSUE TITLE
NAT-Gateway für private Cloud Netzwerke einrichten

### ISSUE THREAD

**Issue by kemcon** [hetzneronline/community-content#624]
## Problem
Leider reicht die Doku nicht. Sie ermöglicht zwar ein ping ins Internet, aber die Namesauflösung funktioniert nicht. Ich denke es liegt daran, dass alle eure Nameserver IPv6 Adressen sind (2a01:4ff:ff00::add:2, 2a01:4ff:ff00::add:1) und eure Anleitung aber nur IPv4 umfasst. Ich habe mir jetzt mit einen IPv4 Eintrag in /etc/systemd/resolved.conf beholfen (https://community.hetzner.com/tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks#configure-route-for-private-networking), aber fände es eigentlich viel besser, wenn die erste Anleitung vollständig wäre. 

## Suggested Fix
Meine Versuche sind kläglich gescheitert. Etwa:
Server mit Internet:
/bin/echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
/sbin/ip6tables -t nat -A POSTROUTING -s '???' -o eth0 -j MASQUERADE

Private Server
/sbin/ip -6 route add default via ?????

**Comment by svenja11** [comment]
Danke für das Feedback @kemcon! Ich habe das Tutorial bearbeitet und einen kurzen Abschnitt zu Nameservern hinzugefügt. Die Hetzner Cloud Netzwerke unterstützen ausschließlich IPv4, daher kann das Tutorial leider nicht für IPv6-Adressen genutzt oder angepasst werden.

**Comment by kemcon** [comment]
Hallo Svenja,

vielleicht wäre es noch sinnvoll, dass es eine „Auf dem Client-Server“ Änderung ist. So steht es bei Schritt 4 zur Unterscheidung.

Kerstin

Von: Svenja Michal ***@***.***>
Gesendet: Dienstag, 6. Juni 2023 15:04
An: hetzneronline/community-content ***@***.***>
Cc: Kerstin Mathaj ***@***.***>; Mention ***@***.***>
Betreff: Re: [hetzneronline/community-content] NAT-Gateway für private Cloud Netzwerke einrichten (Issue #624)


Danke für das Feedback @kemcon<https://github.com/kemcon>! Ich habe das Tutorial bearbeitet und einen kurzen Abschnitt zu Nameservern hinzugefügt. Die Hetzner Cloud Netzwerke unterstützen ausschließlich IPv4, daher kann das Tutorial leider nicht für IPv6-Adressen genutzt oder angepasst werden.
