### ISSUE TITLE
Install and Configure BorgBackup -- Minor mistake in shell script variables

### ISSUE THREAD

**Issue by eriklautenschlaeger** [hetzneronline/community-content#636]
## Problem
In the [quickstart guide](https://borgbackup.readthedocs.io/en/stable/quickstart.html#pitfalls-with-shell-variables-and-environment-variables) it is recommended that 
1.  single quotes are used for the export of environment variables in a script and that
1.  all variables used in borg commands should be exported.

## Suggested Fix
1. In script: Replace corresponding double quotes with single quotes in manual (all languages).
2. In script: Export all variables that are used in borg commands (all languages).

**Comment by eriklautenschlaeger** [comment]
I made a fix, should it be on a separate branch or can I create a pull request directly on master? I am not able to get that information from the [guidelines](https://github.com/hetzneronline/community-content/blob/43025376e675e8dc5e31046d25d077b637aaf544/contributing.md) as it only seems to explain the workflow for new tutorials -- if it's in there sorry and please point me to the correct place.

**Comment by svenja11** [comment]
Thank you for your contribution @eriklautenschlaeger! You  can create a pull request directly on master. 🙂

**Comment by svenja11** [comment]
Fixed with #637
