### ISSUE TITLE
Would you use a beginner step by step tutorial for creating and using an ssh key for windows?

### ISSUE THREAD

**Issue by arye321** [hetzneronline/community-content#656]
Hi, while creating a new server on your service I found it challenging finding resources to help me understand how to create / upload / use / connect with ssh through windows.

this tutorial did help a bit 

https://community.hetzner.com/tutorials/how-to-generate-ssh-key-putty

but I had a number of issues that needed to be done to make the ssh connection work

so, question in the title, so I wont waste hours for nothing

edit: to make it clear , the connection is SSH from a Windows (10) machine to a Linux (Ubuntu) machine

**Comment by alexeygridnev** [comment]
These days, ssh client is included by default into Windows and is accessible via PowerShell. Just open PowerShell and do "ssh username@123.456.789.123" (your Hetzner instance IP address).

**Comment by arye321** [comment]
@alexeygridnev i completely disagree. this would be very hard for a beginner 

![image](https://github.com/hetzneronline/community-content/assets/9559551/63011fd8-d93a-4688-810f-3bea81214ce8)

**Comment by svenja11** [comment]
Closing this issue because of #697
