### ISSUE TITLE
Installation und Konfiguration eines Ubuntu Remote Desktop mit XFCE unter Verwendung von X2Go

### ISSUE THREAD

**Issue by tkinocheck** [hetzneronline/community-content#660]
## Problem

Auf Ubuntu 22 ist der neue User nicht automatisch in der sudoer File

## Suggested Fix

Hinzufügen des zusätzlichen Schritt:

`usermod -aG sudo username`

**Comment by svenja11** [comment]
Danke für den Hinweis @tkinocheck! Ich habe den Schritt eben hinzugefügt.
