### ISSUE TITLE
How to install Ubuntu 20.04 with full disk encryption

### ISSUE THREAD

**Issue by Ali-Razmjoo** [hetzneronline/community-content#663]
## Problem

Hi,

I have spent a couple of days debugging the issue I am facing after encryption following the [article](https://community.hetzner.com/tutorials/install-ubuntu-2004-with-full-disk-encryption), and I thought maybe it worth sharing and fixing.  When I followed this article step by step, everything seemed to work fine, but there were three errors while I was trying to automate the deployments. 

1. In the autosetup file, if you don't add `USE_KERNEL_MODE_SETTING yes` installing grub bootloader might return an error race conditionally; I couldn't figure out why, so I just added the key and value to the setting.
2. While encrypting the disk on CAX VMs (ARM64); the correct SSH Dropbear path is `/etc/dropbear-initramfs/` instead of `/etc/dropbear/initramfs/`.
3. Third and most annoying one was when I had a private network card; I thought the process was failing because I couldn't reach out to SSH; it turned out it was RFC3442 hook which adds private IP route as a priority, and I couldn't reach out to SSH from public IP. The way to do this was to disable the private card and connect it after the encryption is done and the system is booted up (or add the IP route via `ip -4 route add ${net_address}/${net_length} default via ${gateway} dev ${interface}` which I think (didn't test it tho) is something like `ip -4 route add 1.1.1.1/32 default via 172.31.1.1 dev eth0` or could be `eth1`? :D 

Bests, Ali.

## Suggested Fix

Maybe add the notes to the article.

**Comment by sebastianriemer** [comment]
I can confirm the part with the dropbear-path! Instead of 

> mkdir -p /etc/dropbear/initramfs
> cp -a /root/.ssh/authorized_keys /etc/dropbear/initramfs/authorized_keys


use

> mkdir -p /etc/dropbear-initramfs
> cp -a /root/.ssh/authorized_keys /etc/dropbear-initramfs/authorized_keys

Dropbear will issue a warning on the console if you got it wrong:

`dropbear: WARNING: Invalid authorized_keys file, remote unlocking of cryptroot via SSH won't work!`

**Comment by frederikhors** [comment]
From https://www.cyberciti.biz/security/how-to-unlock-luks-using-dropbear-ssh-keys-remotely-in-linux/:

> A note about config file locations:

> The latest version of Debian (such as 12+), Ubuntu (22.04 LTS+), Linux Mint, and Pop!_OS uses the following new version config files and directories:
> 
> New Directory: /etc/dropbear/initramfs/
> New config file: /etc/dropbear/initramfs/dropbear.conf
> New files containing public keys for public key authentication: /etc/dropbear/initramfs/authorized_keys

> The Older version (such as Debian 11 or Ubuntu 20.04 LTS) used the following config files:
> 
> Old Directory: /etc/dropbear-initramfs/
> Old config file: /etc/dropbear-initramfs/config
> Old files containing public keys for public key authentication: /etc/dropbear-initramfs/authorized_keys

**Comment by VectorHektor** [comment]
https://github.com/hetzneronline/community-content/pull/691
