### ISSUE TITLE
Remote domain backups on managed servers

### ISSUE THREAD

**Issue by TheeKuZu** [hetzneronline/community-content#665]
Hi everyone,

Would be great if someone could release a tutorial for remote backups of managed servers. You know to follow the 3-2-1 rule. As I cannot find a decent tutorial anywhere on the internet specifically for Hetzner managed servers. (Unless I am looking in the wrong places)

Have a great day everyone!

**Comment by svenja11** [comment]
Hello @TheeKuZu!
Hetzner automatically creates backups of your Manged Servers. You can restore them via [konsoleH](https://konsoleh.hetzner.com/). If you want to create your own backups, you can check out one of those tutorials, for example:
* [Backup Script for Duplicity](https://community.hetzner.com/tutorials/duplicity-script)
* [Install and configure borgmatic](https://community.hetzner.com/tutorials/install-and-configure-borgmatic)

duplicity should already be installed on the server. If you're not using an SSH key, remember to uncomment `BPASSWORD='yourpass'`

If you want to install borgmatic, you might want to check out the official documentation:
https://torsion.org/borgmatic/docs/how-to/set-up-backups/#non-root-install
https://borgbackup.readthedocs.io/en/stable/installation.html#standalone-binary
