### ISSUE TITLE
Installing Windows without KVM

### ISSUE THREAD

**Issue by 1rfsNet** [hetzneronline/community-content#666]
## Problem
There is a discrepancy in the instructions:

Step 1:
Start parted on the desired drive:
parted /dev/sd**b**

However, further down in the summary it says:
parted /dev/sd**a**

Furthermore sda is used in the vnc command.

## Suggested Fix
Replace parted /dev/sd**b** with parted /dev/sd**a**

**Comment by svenja11** [comment]
@1rfsNet Thank you for pointing this out!
