### ISSUE TITLE
How to install Ubuntu 20.04 with full disk encryption

### ISSUE THREAD

**Issue by fol-ly** [hetzneronline/community-content#676]
## Problem
The installation is canceled due to this line `PART /boot ext4 1G` in `/tmp/setup.conf`

## Suggested Fix
Replace this line with `PART /boot/efi esp 256M` in `/tmp/setup.conf`

**Comment by svenja11** [comment]
Hello @fol-ly 🙂
I tested the tutorial and everything works just fine for me. Did you follow the tutorial directly or did you do anything differently?

**Comment by frederikhors** [comment]
`1G` works good too.

**Comment by svenja11** [comment]
Closing this issue becaue of the comments above.
