### ISSUE TITLE
Securing the SSH service

### ISSUE THREAD

**Issue by gumbo2k** [hetzneronline/community-content#709]
## Problem
Setting `PasswordAuthentication no` only solves half the problem for non-root users. 
Setting `PasswordAuthentication no` but **Ignoring** `ChallengeResponseAuthentication` in this guide leaves users to think they are safe to use weak passwords for non-root users.

It is not even new knowledge and I am surprised to find this misleading/incomplete  information on a Hetzner article...

It is so old that it is even part of LPIC2: https://lpic2book.github.io/src/lpic2.212.3/#allow-or-deny-root-logins
> If you want to fully disable password based logins, the following sshd_config settings should be set to no:
> * PasswordAuthentication
> * ChallengeResponseAuthentication
> * UsePAM
 
## Suggested Fix

Change 
> On the Server
>
> Note: After changing the following setting, it is no longer possible to log in with a password via ssh: PasswordAuthentication no.

to 

> On the Server
>
> Note: After changing the following setting, it is no longer possible to log in with a password via ssh: `PasswordAuthentication no` **and** `ChallengeResponseAuthentication no` 

I am aware, that 2FA with TOTP or similar protocols might need ChallengeResponseAuthentication, so I leave it to you to figure out how to enable this, without opening `keyboard-interactive` as a primary way of password-based authentication again.

**Comment by svenja11** [comment]
@BackInBash Can you take a look at this? Would you be interested in providing an update to your tutorial?
