### ISSUE TITLE
Как утановить MikroTik CHR на Hetzner Cloud

### ISSUE THREAD

**Issue by Wasp-city** [hetzneronline/community-content#718]
## Problem
Good afternoon. It seems to me that there is an error in this article. The article describes setting up CHR, and also describes setting up a fasttrack connection. But fasttrack connection is supported only by hardware routers. https://wiki.mikrotik.com/wiki/Manual:IP/Fasttrack
## Suggested Fix

**Comment by svenja11** [comment]
Thank you for your feedback @Wasp-city!
