### ISSUE TITLE
SQL Server - is it in line with the guidelines?

### ISSUE THREAD

**Issue by alexeygridnev** [hetzneronline/community-content#719]
Hi,
In the contributor guidelines, I see the following: "If your tutorial includes products or software of a third party, make sure they are free-of-charge and open-source, so that everyone can follow your tutorial". SQL Server is obviously not open source but its Express edition is free to use for any purposes including the commercial ones and Developer edition is free to use for development, non-production purposes. It is OK to write a tutorial on deploying SQL Server instance on Hetzner VPS or will it violate the guidelines?

Thanks!

**Comment by svenja11** [comment]
Hello @alexeygridnev
Thank you for double-checking. Since those two editions are free, it is fine and you can write a tutorial about it. 🙂
