### ISSUE TITLE
How to install MikroTik CHR on Hetzner Cloud

### ISSUE THREAD

**Issue by Singlesw** [hetzneronline/community-content#721]
## Problem
in lan configuration interface don't link up until you set mtu 1450
in instruction on - https://community.hetzner.com/tutorials/mikrotik-chr-basic-setup 
don't say this
## Suggested Fix

**Comment by svenja11** [comment]
Thank you for your feedback @Singlesw. The tutorial was tested and it seemed to work. I also checked the official documentation and it did not mention anything about it. For this reason, I will close the issue now.

However, if you disagree and you have a link that supports your suggestion, please share it and I will review this issue again.
