### ISSUE TITLE
Time to publish ready tutorials

### ISSUE THREAD

**Issue by engahmedgad** [hetzneronline/community-content#73]
How long it takes to publish an approved pull request from here to Hetzner community web page ?

**Comment by n-se** [comment]
First of all the pull request gets reviewed by a community manager. Than it will be merged to the master branch.
The community managers mostly work only Monday - Friday so don't expect a merge on a weekend.

For example  #59 was merged on Friday and is already published on the community web page.

**Comment by fdrechsler** [comment]
Exactly like that. 
Every merge triggers a Pipeline internal that generates a Review Instance of the Community Portal, after this has been Reviewed, changes are live :)
