### ISSUE TITLE
A great Tutorial Template!

### ISSUE THREAD

**Issue by snikolaj** [hetzneronline/community-content#736]
## Problem
On the page [A great Tutorial Template! | Hetzner Community](https://community.hetzner.com/markdown-test-suite/), the example-tutorial-files.jpg image is missing and the link for the license block on the website (https://github.com/hetzneronline/community-content/blob/master/tutorial-template.md?plain=1#L96-L125) points to lines 96-125 in the Markdown file, which was valid for a previous version of the document, but the document is updated and now the right lines for the license block are 108-137 (the link would then be https://github.com/hetzneronline/community-content/blob/master/tutorial-template.md?plain=1#L108-L137).
## Suggested Fix
Find the location of the image file, update it and change the link for the license block from https://github.com/hetzneronline/community-content/blob/master/tutorial-template.md?plain=1#L96-L125 to https://github.com/hetzneronline/community-content/blob/master/tutorial-template.md?plain=1#L108-L137.

**Comment by svenja11** [comment]
Thank you for pointing this out @snikolaj!
