### ISSUE TITLE
How to set up NAT gateway for private Cloud Networks

### ISSUE THREAD

**Issue by VoxoLone** [hetzneronline/community-content#767]
I followed the [guide](https://community.hetzner.com/tutorials/how-to-set-up-nat-for-cloud-networks), and it works just fine, but because I am not that familiar with networking stuff, can I achieve high availability with this? I can only set up one route 0.0.0.0/0 pointing to one gateway server with internet access. But if I want multiple servers, in each location (nbg, fsn and hel) the pings get bad for the servers in the location hel if the gateway is in fsn or nbg (25-30 ms). So my question is, if I can set up one gateway in each location and use the fastest one with ping checks from the servers without internet or is it impossible because I can only define one gateway route in a private network.

**Comment by svenja11** [comment]
Hello @VoxoLone
Unfortunately, this is not possible. In each Cloud Network, you can only set up one route for `0.0.0.0/0`. If you wanted to point at different servers, you would have to use one Cloud Network for each location and use something like WireGuard to connect those private networks (see [Setting up a VPC with site-to-site VPN in Hetzner Cloud](https://community.hetzner.com/tutorials/vpc-with-wireguard-pfsense#step-1---planning)). However, with this setup, the internal ping would get worse. I know this is probably not the answer you hoped for but I hope it still helps.
