### ISSUE TITLE
How to route cloud server over private network using pfSense and Hetzner Cloud Networks

### ISSUE THREAD

**Issue by germebl** [hetzneronline/community-content#769]
### Setup
OPNSense instead of PfSense

## Problem
I've setup everything as you wrote, but the Outbound NAT isn't working as it should. I can connect via SSH over OPNSense to the LAN address of the client-server. When doing the MTR the hops are:
1.: hetzner lan gw (so its correct)
2.: lan-ip of OPNSense (still correct)
3.: hetzner lan gw (not correct)

I think there is something not working as intended with the Outbound NAT. 

In my understanding the Outbound NAT Rule should translate everything from the lan subnet to the wan address, which should then use the WAN gateway - but its using again the LAN gateway and i think that's the reason for the routing loop.

I've checked the post multiple times and set up everything as you do. I did not done any step other way than you.

## Another test
I just tested if i can ping google.de from the OPNSense - its only doing ipv6 - ipv4 does not work. Then i tried to traceroute to google with ipv4 and ipv6. The v4 traceroute has the lan gateway as its first hop, the ipv6 goes over fe80::%vtnet0 so correctly over the WAN.

So something with IPv4 does not work as intended. So i checked the IPv4 DHCP: IP-address/32 with GW 172.31.1.1 which should be fine.

## Suggested Fix
Actually unknown

## Question
Does someone know if there is still something missing, any known bug exists or a fix for that?

**Comment by svenja11** [comment]
@germebl I just tested the tutorial with pfSense and it works perfectly fine. This means the issue is definitely with OPNsense. Since our tutorial is for pfSense, it means that unfortunately I cannot help you with this. Were you able to find the issue yourself by now?

**Comment by germebl** [comment]
@svenja11 i've tested around and the issue was the wrong default gateway. I tried to reproduce the issue and the problem was, when i've created the LAN it got automatically default gateway, instead of the WAN gateway remaining the default gateway as it was before adding LAN.
