### ISSUE TITLE
Install TURN/STUN Server on Debian/Ubuntu with coturn

### ISSUE THREAD

**Issue by BigHoss** [hetzneronline/community-content#772]
## Problem

[certbot-auto is deprecated](https://eff-certbot.readthedocs.io/en/latest/install.html#certbot-auto-deprecated) and should not be used anymore

## Suggested Fix
show another way to install certbot ([cme.sh for example](https://github.com/acmesh-official/acme.sh))

**Comment by svenja11** [comment]
Thank you @BigHoss for pointing this out!
