### ISSUE TITLE
Add Hetzner Firewall Configuration Details

### ISSUE THREAD

**Issue by miah0x41** [hetzneronline/community-content#776]
Is it possible to add how to use Hetzner Firewall to secure the Wireguard service?

**Comment by svenja11** [comment]
* @wpdevelopment11 You wrote [Installing and configuring WireGuard VPN on Ubuntu](https://community.hetzner.com/tutorials/install-and-configure-wireguard-vpn)
* @benglvr You wrote [Installing and configuring a WireGuard VPN server on Debian](https://community.hetzner.com/tutorials/install-and-configure-wireguard-vpn-debian)

-------------

@wpdevelopment11 and @benglvr, can you take a look at this issue? Would you be interested in adding this to your tutorial?

**Comment by svenja11** [comment]
Fixed with #779

**Comment by miah0x41** [comment]
Thanks for updating!
