### ISSUE TITLE
Enabling the iGPU on Intel Processors

### ISSUE THREAD

**Issue by webpymes** [hetzneronline/community-content#785]
## Problem 
sudo intel_gpu_top
no device filter specified and no discreate/integrated i915 devices found
## Suggested Fix
¿?

**Comment by svenja11** [comment]
Did you remove "nomodeset" as explained in [step 4](https://community.hetzner.com/tutorials/howto-enable-igpu#step-4---adjust-the-grub-settings)?

@BackInBash You wrote [the tutorial](https://github.com/hetzneronline/community-content/tree/master/tutorials/howto-enable-igpu). Can you take a look at this and check if you need to update your tutorial?

**Comment by BackInBash** [comment]
Hi @svenja11 

I don't have an appropriate server to test or reproduce the tutorial.
Could you provide me a few servers with newer Intel CPUs so I can test them?

**Comment by svenja11** [comment]
@BackInBash I see. Unfortunately, I don't think that's possible. It could also be possible that the tutorial is fine and this is not a general error.

@webpymes Can you provide more information on your setup and double-check if you accidentially skipped any steps as suggested in my response above? Maybe you can check the output of `cat /proc/cmdline`. The output should not include "nomodeset".

**Comment by webpymes** [comment]
My Console is:
> /etc/default/grub.d/hetzner.cfg

GRUB_HIDDEN_TIMEOUT_QUIET=false
GRUB_CMDLINE_LINUX_DEFAULT="consoleblank=0"

# only use text mode - other modes may scramble screen
GRUB_GFXPAYLOAD_LINUX="text"

**Comment by BackInBash** [comment]
@webpymes could you provide the output of `lscpu`?

**Comment by BackInBash** [comment]
@svenja11 Kann geschlossen werden AMD CPUs haben i.d.R keine iGPU.
