### ISSUE TITLE
Установка и настройка BorgBackup

### ISSUE THREAD

**Issue by zTechGit** [hetzneronline/community-content#786]
## Problem
Step 3.2 RU

EN: But you also have to be aware that each file is saved exactly once. Should a file be damaged by a disk failure, for example, this file will be corrupted in all following backups.

## Suggested Fix

RU: Однако же следует помнить, что каждый файл хранится только один раз. В случае повреждения файла, например, при сбое диска, он будет повреждён во всех последующих резервных копиях.

**Comment by svenja11** [comment]
Thank you for the suggestion @zTechGit
