### ISSUE TITLE
Install and Configure Nextcloud Office

### ISSUE THREAD

**Issue by zuron7** [hetzneronline/community-content#788]
## Problem

Restrict Usage only to your Nextcloud Instance

- Currently anyone can use your collabora server as there is no whitelisted/allowed domains or users. 

## Suggested Fix

Follow this guide:  https://www.collaboraoffice.com/code/linux-packages/

follwed  by this guide; https://sdk.collaboraonline.com/docs/installation/Configuration.html

Just putting these two links at the end of the documentation should help the end user configure the document better.

**Comment by svenja11** [comment]
Fixed with #790
