### ISSUE TITLE
Installing Windows without KVM

### ISSUE THREAD

**Issue by ls-msc** [hetzneronline/community-content#797]
## Problem
Doesn't work on UEFI machines, because it doesn't install the EFI boot loader.

## Suggested Fix
Start qemu with UEFI bios
qemu-system-x86_64 **-bios /usr/share/ovmf/OVMF.fd** -enable-kvm -smp 48 -m 16g -boot d -cdrom SW_DVD9_Win_Server_STD_CORE_2022_2108.15_64Bit_English_DC_STD_MLF_X23-31801.ISO -drive file=/dev/nvme3n1,format=raw,media=disk -vnc 127.0.0.1:1

**Comment by svenja11** [comment]
Thank you for your suggested fix @ls-msc!
