### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by Kjarrigan** [hetzneronline/community-content#8]
Hi there,

it's cool to see that there are already a few tutorials incoming. One remark though - these texts will naturally be quite long so personally I really like to have a ToC at the top so I can jump to a specific step really easily (e.g. because I stopped reading there the last time or because I want to re-read a specific step which I have forgotten).

So I propose to:
* add a ToC on every tutorial
* add an entry to the guideline that this is obligatory
* or add an CI run that autogenerates and appends one to the file (I have done this in a project and it works quite well)

**Comment by fdrechsler** [comment]
Hey There Kjarrigan. 

Actually, this is already happening. We are generating static pages with [GatsbyJS](https://github.com/gatsbyjs/gatsby) and generate a ToC with [remark-toc](https://github.com/remarkjs/remark-toc).

So no one needs to write ToC's.

**Comment by Kjarrigan** [comment]
Awesome. So maybe instead a small hint anywhere that this is done automatically.
