### ISSUE TITLE
Connect to server over private network with Cloudflare Access

### ISSUE THREAD

**Issue by kitro** [hetzneronline/community-content#807]
https://community.hetzner.com/tutorials/connect-over-pvt-net-with-cloudflare-access

## Problem
In the step Step 4 - Tightening Hetzner Firewall rules, how I can block only the ssh in port 22 from public ip? should I do it in inbound only and outbound? 

Thanks!

## Suggested Fix

**Comment by svenja11** [comment]
Hello @kitro,
I'm not sure if I understand your question correctly. Would you like to know how you can block incoming requests to port 22 only for public IPs, meaning that you can still establish a connection via a private IP?

----------------

In this case, the rule mentioned in the tutorial should be enough:

* Inbound
  
  | Sources                                 | Protocol | Port | Port range |
  | --------------------------------------- | -------- | ---- | ---------- |
  | <kbd>Any IPv4</kbd> <kbd>Any IPv6</kbd> | TCP      | 22   |

* Outbound
  
  If you don't add any outbound rules, your server can send request to any address. If you add a rule, your server can only send requests to the IP addresses listed in the rules you added. All other connections will be dropped. In many cases, you don't need any outbound rules. 

The inbound rule above will block all incoming requests to port 22 that are send via the public network, such as `ssh root <public_ip>:22`. The Firewall does NOT apply to the private network. This means, you can still access the server via its private IP, for example: `ssh root@<private_ip>:22`

-----------------

Does this answer your question?

**Comment by kitro** [comment]
Hi @svenja11 , 

Thank you for you reply, Yes I want to let only the ssh with the private ip, and blocked the ipv4, ipv6, 
I'm using Hetzner firewall , If I'm understand correctly the Inbound section is to allow which IP Addresses can access. 

<img width="1094" alt="image" src="https://github.com/hetzneronline/community-content/assets/5256921/9d759c58-fccc-4eda-910d-b0dbec05ae80">

If I set the rules in inbound like the image above, mean allow only the ipv4, ipv6 to ssh, and block all other ports. 
I want the reverse rule allow everything but only block ssh (port: 20) from ipv4, ipv6 access.

Thank you!

**Comment by kitro** [comment]
Hi!
I resolved it by specifying explicitly all allowed ports in inbound rules.
Thank you so much!
