### ISSUE TITLE
Question about tagging Hetzner on Model Hub

### ISSUE THREAD

**Issue by stefan-it** [hetzneronline/community-content#808]
Hi everyone,

I have already trained/fine-tuned models on my great GEX44 and want to uploaded these on the model hub (find me [here](https://huggingface.co/stefan-it)).

The Hetzner GPU server pages states:

![image](https://github.com/hetzneronline/community-content/assets/20651387/b5d3d76b-f627-4309-a58d-ec432abe5ca2)

Now I would like to ask what is best way to mention/tag Hetzner. E.g. it would be possible to make use of the metadata feature for a model card:

```
tags:
- hetzner-gex44
- hetzner
- hetzner-gpu
```

When you specifiy a tag in the metadata section of a model card, then it is relatively easy to filter and search for them:

```bash
https://huggingface.co/models?other=hetzner
```

Do you have any preference for that :thinking:

**Comment by stefan-it** [comment]
Pinging @svenja11 who wrote Chatbot tutorial :)

**Comment by svenja11** [comment]
Hello @stefan-it 🙂
It's great to hear that you're enjoying your GEX44!

Yes you can tag Hetzner via the metadata. This way, you should get proper labels:

![huggingface tags marked](https://github.com/hetzneronline/community-content/assets/84835304/2b79c26f-bcc3-4fd7-b654-0b651a335a6a)

Regarding the tags themselves, it is definetly best when you add `hetzner`, and `hetzner-gex44` would also be great. All other tags, such as `hetzner-gpu`, are just nice-to-have. 🙂

**Comment by stefan-it** [comment]
Hi @svenja11 ,

thanks for the quick reply! I used the tags for uploading my latest [models](https://huggingface.co/models?other=hetzner) :)
