### ISSUE TITLE
Hosting an AI chatbot with Ollama and Open WebUI

### ISSUE THREAD

**Issue by christrille** [hetzneronline/community-content#809]
## Problem: el código de la sección "Install Open WebUI manually" indica:

cp -RPp example.env .env

## Suggested Fix: creo que tendría que ser (No 100% seguro - estoy todavía probando.):
cp -RPp .env.example .env

O sea:
cambiar:  example.env .env
por:         .env.example .env

**Comment by svenja11** [comment]
Hello @christrille 
I just checked the file name and you're absolutely right. Thank you for pointing this out!
