### ISSUE TITLE
Setting up a Let's Encrypt certificate on cloud load balancers with external domain

### ISSUE THREAD

**Issue by kikoncuo** [hetzneronline/community-content#816]
## Problem
It skips over the only step that everyone is looking for
How do I use the certificate after creating it? How do I assign it to a load balancer?
It just says " Now the DNS entries required for the respective service can be created with target on the load balancer."
I get that I have to go into DNS configuration and create a new record pointing to the IP of the load balancer (Which is also not clear)
But then, how does the load balancer know which certificate to use? How do I configure that?

## Suggested Fix
Explain the last steps

**Comment by svenja11** [comment]
Hello @kikoncuo!
This is explained in "Step 3 - Setting up the Load Balancer". To add the certificate to the Load Balancer, you need to navigate to your Load Balancer and select the upper menu option "Services". There, click on `Add service`» `TLS Termination`.

When you create the service, you can select `CERTIFICATES` » `+ Add certificates` and create a new certificate.  After you saved the service, the Load Balancer should use the certificate added to that service.

-----

I just created a PR (#817) to update some explanations and add new screenshots, so hopefully this is easier to follow now.
