### ISSUE TITLE
Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud - Volumes

### ISSUE THREAD

**Issue by d3fragg3d** [hetzneronline/community-content#831]
Hello,

I was just reading your article -> Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud
Absolutely excellent and exactly what I wanted.
However you do not mention how to add persistent volumes, perhaps with longhorn?

Do you have any information on this? I feel its the only thing thats missing which is specifically around hetzner cloud.

Thanks

Chris

**Comment by svenja11** [comment]
@Blue25GD You wrote the tutorial. Can you take a look at this?

**Comment by Blue25GD** [comment]
I'm sorry @d3fragg3d, I do not have any experience using Longhorn or this kind of volume system, maybe I'll add something like this once I get the time to learn it. Thanks for your suggestion, I'll create a follow up to this issue whenever I add something related to volumes to the article.

**Comment by svenja11** [comment]
Closing because of comment above.
