### ISSUE TITLE
How to protect a website with Cloudflare without exposing ports to the Internet

### ISSUE THREAD

**Issue by EspoTek** [hetzneronline/community-content#839]
URL:
https://community.hetzner.com/tutorials/cloudflare-website-protect

## Problem
In the Python code, `get_cloudflare_ips` returns an empty list [] if the request to Cloudflare fails.
This means that if there was a temporary error (e.g. 500 on Cloudflare's end), the firewall would be configured to block _all_ traffic on port 443 until the cron job re-ran.

## Suggested Fix
Changing the function to something like this would be a quick fix:
```
def get_cloudflare_ips(version):
    url = "https://www.cloudflare.com/ips-v" + version
    response = requests.get(url)
    if response.status_code == 200:
        return response.text.strip().split('\n')
    else:
        raise Exception("Failed to retrieve Cloudflare IP ranges", response)
```
This way, if the cron job fails to get the IP ranges for any reason, it will just blow up and not configure the firewall badly.

**Comment by svenja11** [comment]
Thank you @EspoTek!
