### ISSUE TITLE
Markdown Test Suite

### ISSUE THREAD

**Issue by fdrechsler** [hetzneronline/community-content#85]
Internally the Community Manager checks the Markdown with this tool:

https://community.hetzner.com/markdown-test-suite/

Thought I release it publicly, is that useful to you guys?
If it is, we should add it to the Readme.

**Comment by n-se** [comment]
The navigation (scrolling and right/left sharing) is a bit unique, but it is really good for testing how it looks like later on the community website.

**Comment by fdrechsler** [comment]
Okay, i see what you mean. Just tested it on Ubuntu, that's something not appearing on MacOS for some Reason. But as Dev-Tool it's still fine i guess.

**Comment by n-se** [comment]
Got this added anywhere? Or why did you decided to close it?
