### ISSUE TITLE
A simple installation guide for Nginx Proxy Manager

### ISSUE THREAD

**Issue by schnillerman** [hetzneronline/community-content#861]
## Problem
This doesn't work with containers other than nginx.

## Suggested Fix
Add `network_mode: "host"` to the Nginx PM docker compose file since 127.0.0.1 inside the NPM container is not going to be the same localhost for other containers.

**Comment by svenja11** [comment]
@Techout592 you wrote [the tutorial](https://github.com/hetzneronline/community-content/tree/master/tutorials/installing-nginx-proxy-manager). Could you take a look at this issue and update the tutorial if needed?

**Comment by schnillerman** [comment]
💪🏼
