### ISSUE TITLE
Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud

### ISSUE THREAD

**Issue by maxiar** [hetzneronline/community-content#867]
## Problem
In the line: 
Also, we're disabling traefik because we'll be using nginx as an ingress controller for later on.
## Suggested Fix
Add the missing part from the tutorial to complete the k3s cluster creation with a fully working nginx/load balancer services.

**Comment by svenja11** [comment]
@Blue25GD you wrote [the tutorial](https://github.com/hetzneronline/community-content/tree/master/tutorials/setup-your-own-scalable-kubernetes-cluster). Could you take a look at this issue?
