### ISSUE TITLE
Managing Kubernetes on Hetzner with Cluster API

### ISSUE THREAD

**Issue by noelhermans** [hetzneronline/community-content#891]
## Problem
The secret reference in the deployment hcloud-cloud-controller-manager is incorrect
## Suggested Fix
        - name: HCLOUD_TOKEN
          valueFrom:  
            secretKeyRef:  
               key: hcloud 
              name: hetzner

**Comment by svenja11** [comment]
@syself you wrote [the tutorial](https://github.com/hetzneronline/community-content/blob/master/tutorials/kubernetes-on-hetzner-with-cluster-api/01.en.md). Could you please take a look at this issue and update the tutorial as needed.

**Comment by svenja11** [comment]
Thank you for your feedback @noelhermans!
