### ISSUE TITLE
How to set up NAT gateway for private Cloud Networks working for ubuntu 22 server?

### ISSUE THREAD

**Issue by B87** [hetzneronline/community-content#913]
## Problem
I cannot reproduce the example using cloud config yml in ubuntu 24 servers

Im using the example below and the nat client is still not able to access the network

iptables -t nat -L on NAT public server returns

`MASQUERADE  all  --  10.0.0.0/16          anywhere `

ip route show on private server returns
```
10.0.0.0/16 via 10.0.0.1 dev enp7s0 proto dhcp src 10.0.0.4 metric 1002 mtu 1450 
10.0.0.1 dev enp7s0 proto dhcp scope link src 10.0.0.4 metric 1002 mtu 1450 
169.254.169.254 via 10.0.0.1 dev enp7s0 proto dhcp src 10.0.0.4 metric 1002 mtu 1450 
```

**Comment by svenja11** [comment]
Thank you for your feedback @B87! I just updated cloud-init in the tutorial.
