### ISSUE TITLE
Tutorial Website has missing links

### ISSUE THREAD

**Issue by arnabJ** [hetzneronline/community-content#920]
Issue:
1. The search bar doesn't do anything. I tried pressing the enter key after typing my query. There is no search button beside the search input box.
2. The pagination links at the bottom are not present. All the page buttons have a "#" for their href. Clicking on any button just scrolls the webpage to the top as expected of a "#" link.

Result:
I can't search or navigate through different pages of the Tutorials. Only the 1st page is accessible with its 10 tutorials.

Expectation:
1. The search bar should work and tutorials matching the query should be fetched.
2. The pagination buttons should have proper page links so that we can navigate between different pages.

![Screenshot 2024-08-23 at 8 04 59 AM](https://github.com/user-attachments/assets/4cea6935-1d3c-454e-8839-877b37afed88)

**Comment by svenja11** [comment]
Thank you for pointing this out @arnabJ! I will forward this to our website team

**Comment by wpdevelopment11** [comment]
Looks like you have disabled JavaScript in your browser. Works fine for me.

**Comment by svenja11** [comment]
They’ve actually already fixed it in the meantime 🙂
