### ISSUE TITLE
Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud - failed to create 3 workers

### ISSUE THREAD

**Issue by stokmanis** [hetzneronline/community-content#933]
Hi,

I folowed the tutorial and entered in the resource worker-nodes count = 3. It created master-node, first worker-node, but failed to create remaining worker nodes.

hcloud_server.worker-nodes[0]: Creation complete after 22s [id=52491574]
╷
│ Error: Primary IP limit exceeded (resource_limit_exceeded, 971c2996dc2dd6c0)
│ 
│   with hcloud_server.worker-nodes[2],
│   on main.tf line 56, in resource "hcloud_server" "worker-nodes":
│   56: resource "hcloud_server" "worker-nodes" {
│ 
╵
╷
│ Error: server limit exceeded (resource_limit_exceeded, d1798f30e86aa508)
│ 
│   with hcloud_server.worker-nodes[1],
│   on main.tf line 56, in resource "hcloud_server" "worker-nodes":
│   56: resource "hcloud_server" "worker-nodes" {

**Comment by Tom3201** [comment]
Hi,
You seem to have reached the resource limit of active servers for your cloud account. You can view the current limits in the Cloud Console in the “Limits” menu. If necessary, you should also be able to request a limit increase there.

**Comment by svenja11** [comment]
Closing this issue because of comment above.
