### ISSUE TITLE
Install and Configure BorgBackup

### ISSUE THREAD

**Issue by adcin** [hetzneronline/community-content#953]
## Problem

The link is broken:

For more explanation, check out the official Storage Box documentation on [setting up an SSH key](https://docs.hetzner.com/robot/storage-box/backup-space-ssh-keys). You will need to follow the instructions on port 23.

## Suggested Fix

Broken link:  https://docs.hetzner.com/robot/storage-box/backup-space-ssh-keys
Correct link: https://docs.hetzner.com/storage/storage-box/backup-space-ssh-keys

**Comment by adcin** [comment]
Same issue in this FAQ:
https://docs.hetzner.com/storage/storage-box/access/access-ssh-rsync-borg/

**Comment by svenja11** [comment]
Thank you for pointing this out @adcin!
