### ISSUE TITLE
How to protect a website with Cloudflare without exposing ports to the Internet

### ISSUE THREAD

**Issue by ChristianIvicevic** [hetzneronline/community-content#964]
## Problem

The page suggests that the crontab expression `* 0 * * * /usr/bin/python3 /path/to/firewall.py` runs once a day, but it runs every minute instead.

## Suggested Fix

Replace with `0 0 * * * /usr/bin/python3 /path/to/firewall.py`

**Comment by svenja11** [comment]
Thank you for pointing this out @ChristianIvicevic! I will fix it.
