### ISSUE TITLE
Use avatars.githubusercontent.com instead of avatarsX. for author_img

### ISSUE THREAD

**Issue by n-se** [hetzneronline/community-content#98]
I think it would make sense to replace all `avatarsX.githubusercontent.com` URLs in `author_img` with just `avatars.githubusercontent.com` to have a clear structure here too.

In their API, e.g. https://api.github.com/users/hetzneronline, they have `avatarsX` in the URL, but as far as I can see all author images are available on all subdomains of this type.

**Comment by n-se** [comment]
Not for now. Closing this...

**Comment by RullDev** [comment]
![Uploading f7e31f84-d1a0-4977-8d65-2018ba5f0eeb.jpeg…]()
