### ISSUE TITLE
How to install Arch Linux on a Hetzner Cloud server

### ISSUE THREAD

**Issue by rfoerthe** [hetzneronline/community-content#984]
## Problem
I think the command 'genfstab -U /mnt >> /etc/fstab' updates the wrong fstab file (the one of the bootstrap env).
## Suggested Fix
Run the corrected command after pacstrap in step 2:
genfstab -U /mnt >> /mnt/etc/fstab

**Comment by wpdevelopment11** [comment]
Duplicate of #956
